[build]
  command = "npm run prebuild && npm run build"
  publish = ".next"

[build.environment]
  NEXT_CACHE = ".next/cache"
  STRAPI_BASE_URL = "https://api.popnails.cz" # Задаем переменную окружения
