[build]
  command = "npm run prebuild && npm run build"
  publish = "out" # Указываем папку, куда Next.js будет собирать проект

[build.environment]
  STRAPI_BASE_URL = "https://api.popnails.cz" # Задаем переменную окружения
